version: 2
jobs:
  node 8:
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: update npm
          command: npm install -g npm@6
      - run: npm ci
      - run: npm test
  node 10:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm test
  node latest:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm ci
      - run: npm test

workflows:
  version: 2
  tests:
    jobs:
      - node 8
      - node 10
      - node latest